apiVersion: apps/v1
kind: Deployment
metadata:
  name: agar-deployment
spec:
  selector:
    matchLabels:
      name: agar
  template:
    metadata:
      labels:
        name: agar
    spec:
      containers:
        - name: agarcontainer
          image: henrykum23/agargame:latest
          ports:
            - containerPort: 3000
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 80
          #   initialDelaySeconds: 6
          #   timeoutSeconds: 1
          #   periodSeconds: 5
          #   successThreshold: 1
          #   failureThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: agar-service
spec:
  type: NodePort
  selector:
    name: agar
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000